let PARAMS = {
    state:{
        intro:true,
        variableFont:40,
        oneUser: false,
    },
    posnet: {
        positionHead: null,
        poses: [],
        model: false,
    },
    fontFam: null,
    font: {
        bodyBox:41,
        spacing: 50,
    },
    word: [
        "a",
        // "b",
        // "c",
        // "d",
        // "e",
        // "f",
        // "g",
        // "h",
        // "i",
        // "j",
        // "k",
        // "l",
        // "m",
        // "n",
        // "o",
        // "p",
        // "q",
        // "r",
        // "s",
        // "t",
        // "u",
        // "v",
        // "w",
        // "x",
        // "y",
        // "z"
        // "0123"
    ],
    headType:"0",
    physics: {
        gravityForce:1,
    //     bounds: null,
    //     engine: null,
    //     world: null,
    //     ground: null,
    //     ground2: null,
    //     letterTemplates: {},
    //     bodies:[],
    //     bodiesMaxLength:100,
    //     myWidth:null,
    //     myHeight:null,
    //     grav:null,
    //     theta:null,
    //     fps:30,
    }
}

